; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
lib_deps = 
	m5stack/M5Unified
	bblanchon/ArduinoJson@^7.2.2
	https://github.com/stack-chan/stackchan-arduino#main
	https://github.com/haraisao/m5stack-avatar#dev
	
lib_ldf_mode = deep
board_build.filesystem = littlefs
build_flags = 
    -DBOARD_HAS_PSRAM ; PSRAMを有効化
    -mfix-esp32-psram-cache-issue
upload_port = COM7
